name: Update Job Applications Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:  # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Set up Gmail credentials
        run: |
          mkdir -p config
          echo "${{ secrets.GMAIL_CREDENTIALS_B64 }}" | base64 -d > config/gmail_credentials.json

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: |
          python main.py  # Runs with since_hours=1 (update main.py below)
          python clean_duplicates.py
          python visualize_table.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/job_applications.json data/processed_ids.json TABLE.md visualizations/sankey.html
          if ! git diff --cached --quiet; then
            git commit -m "Automated update: job applications, table, and Sankey chart"
            git push
          else
            echo "No changes to commit."
          fi