name: Job App Tracker Automation

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'  # Runs every hour at the start of the hour (e.g., 1:00, 2:00, etc.)

jobs:
  run-script:
    permissions:
      contents: write  # Explicitly grant write permissions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r job-app-tracker/requirements.txt

      - name: Create Gmail credentials file
        run: |
          mkdir -p config
          echo '${{ secrets.GMAIL_CREDENTIALS }}' | jq . > config/gmail_credentials.json

      - name: Create Gmail token file
        run: |
          echo '${{ secrets.GMAIL_TOKEN }}' | jq . > config/token.json

      - name: Run main script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python job-app-tracker/main.py

      - name: Clean duplicates
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python job-app-tracker/clean_duplicates.py

      - name: Generate visualizations
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python job-app-tracker/visualize_table.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update of job applications, duplicates, and visualizations" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zichengalexzhao/job-app-tracker.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}