name: Update Job Tracker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: write # This line is critical to allow pushing changes

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r job-app-tracker/requirements.txt

      - name: Set up credentials for multiple accounts
        run: |
          mkdir -p config/accounts/personal_gmail
          mkdir -p config/accounts/school_gmail
          echo "${{ secrets.GMAIL_CREDENTIALS_PERSONAL }}" > config/accounts/personal_gmail/gmail_credentials.json
          echo "${{ secrets.GMAIL_TOKEN_PERSONAL }}" > config/accounts/personal_gmail/token.json
          echo "${{ secrets.GMAIL_CREDENTIALS_SCHOOL }}" > config/accounts/school_gmail/gmail_credentials.json
          echo "${{ secrets.GMAIL_TOKEN_SCHOOL }}" > config/accounts/school_gmail/token.json
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > config/.env

      - name: Run the main script to fetch and process applications
        run: python job-app-tracker/main.py

      - name: Clean duplicates from the dataset
        run: python job-app-tracker/clean_duplicates.py

      - name: Generate new table and visualization
        run: python job-app-tracker/visualize_table.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of job applications, duplicates, and visualizations"
            git push
          fi