name: Job App Tracker Automation

on:
  push:
    branches: [main]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r job-app-tracker/requirements.txt  # Updated path

      - name: Create Gmail credentials file
        run: |
          mkdir -p config
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > config/gmail_credentials.json

      - name: Create Gmail token file
        run: |
          echo "${{ secrets.GMAIL_TOKEN }}" > config/token.json

      - name: Run main script
        run: python job-app-tracker/main.py

      - name: Clean duplicates
        run: python job-app-tracker/clean_duplicates.py